





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sitecore.Feature.ChatBot.Models
{
    using System;   
using System.Collections.Generic;  
using System.Collections.Specialized; 
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Rules;

	/*public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}*/
}
namespace SitecoreWebApi.Models.sitecore.templates.Custom
{


 	/// <summary>
	/// IService Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Custom/Service</para>	
	/// <para>ID: fcf391e5-7ce3-49e9-81ec-534238dfa2b7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IServiceConstants.TemplateIdString )] //, Cachable = true
	public partial interface IService : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 9547e694-389b-43fc-96ff-3241cdcce89f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Text field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 376febdd-167f-4525-b8a8-0148d0d371d4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.TextFieldName)]
					string Text  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f60e0922-1d48-4384-8d57-55c4f0c27aad</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}
		
	public static partial class IServiceConstants{

			public const string TemplateIdString = "fcf391e5-7ce3-49e9-81ec-534238dfa2b7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Service";

					
			public static readonly ID ImageFieldId = new ID("9547e694-389b-43fc-96ff-3241cdcce89f");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID TextFieldId = new ID("376febdd-167f-4525-b8a8-0148d0d371d4");
			public const string TextFieldName = "Text";
			
					
			public static readonly ID TitleFieldId = new ID("f60e0922-1d48-4384-8d57-55c4f0c27aad");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Service
	/// <para></para>
	/// <para>Path: /sitecore/templates/Custom/Service</para>	
	/// <para>ID: fcf391e5-7ce3-49e9-81ec-534238dfa2b7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IServiceConstants.TemplateIdString)] //, Cachable = true
	[Serializable]
	public partial class Service  : GlassBase, IService 
	{
	   
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 9547e694-389b-43fc-96ff-3241cdcce89f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Text field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 376febdd-167f-4525-b8a8-0148d0d371d4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f60e0922-1d48-4384-8d57-55c4f0c27aad</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
